<?php $pageTitle = 'Sélection des sièges'; ?>
<?php require_once __DIR__ . '/../layouts/header.php'; ?>

<div class="page-content">
    <div class="container">
        <a href="<?= BASE_URL ?>/index.php?page=movie&action=detail&id=<?= $screening['movie_id'] ?>" class="btn btn-ghost btn-sm mb-32"><i class="fas fa-arrow-left"></i> Retour au film</a>

        <div class="text-center mb-32">
            <h1><?= e($screening['movie_title']) ?></h1>
            <p class="text-muted mt-8">
                <?= date('d/m/Y', strtotime($screening['show_date'])) ?> — <?= date('H:i', strtotime($screening['show_time'])) ?>
                — <?= e($screening['hall_name']) ?> (<?= e($screening['hall_type']) ?>)
                — <?= number_format($screening['price'], 2) ?> DT / place
            </p>
        </div>

        <div class="screen-indicator">Écran</div>

        <div class="seat-grid" id="seatGrid"
             data-rows="<?= $screening['rows_count'] ?>"
             data-cols="<?= $screening['cols_count'] ?>"
             data-screening-id="<?= $screening['id'] ?>"
             data-price="<?= $screening['price'] ?>"
             data-booked='<?= json_encode($bookedSeats) ?>'>
            <!-- Generated by JS -->
        </div>

        <div class="seat-legend">
            <div class="seat-legend-item"><div class="seat seat-available"></div> Disponible</div>
            <div class="seat-legend-item"><div class="seat seat-selected"></div> Sélectionné</div>
            <div class="seat-legend-item"><div class="seat seat-taken"></div> Occupé</div>
        </div>

        <div class="booking-summary" id="bookingSummary" style="display:none;">
            <h3>Résumé de la réservation</h3>
            <div class="summary-row">
                <span>Film</span>
                <span><?= e($screening['movie_title']) ?></span>
            </div>
            <div class="summary-row">
                <span>Séance</span>
                <span><?= date('d/m/Y', strtotime($screening['show_date'])) ?> à <?= date('H:i', strtotime($screening['show_time'])) ?></span>
            </div>
            <div class="summary-row">
                <span>Salle</span>
                <span><?= e($screening['hall_name']) ?></span>
            </div>
            <div class="summary-row">
                <span>Sièges</span>
                <span id="selectedSeatsDisplay">-</span>
            </div>
            <div class="summary-row">
                <span>Prix unitaire</span>
                <span><?= number_format($screening['price'], 2) ?> DT</span>
            </div>
            <div class="summary-row total">
                <span>Total</span>
                <span id="totalPriceDisplay">0 DT</span>
            </div>

            <form method="POST" action="<?= BASE_URL ?>/index.php?page=booking&action=confirm" id="bookingForm" class="mt-24">
                <input type="hidden" name="screening_id" value="<?= $screening['id'] ?>">
                <input type="hidden" name="seats" id="seatsInput" value="[]">
                <button type="submit" class="btn btn-primary btn-block" id="confirmBtn">Confirmer la réservation</button>
            </form>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/../layouts/footer.php'; ?>
<script src="<?= BASE_URL ?>/assets/js/seats.js"></script>
